//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.LayoutRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayoutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.LayoutRules.LayoutResources", typeof(LayoutResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align braces.
        /// </summary>
        internal static string SA1500CodeFix {
            get {
                return ResourceManager.GetString("SA1500CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand single line block.
        /// </summary>
        internal static string SA1501CodeFix {
            get {
                return ResourceManager.GetString("SA1501CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all single line blocks.
        /// </summary>
        internal static string SA1501CodeFixAll {
            get {
                return ResourceManager.GetString("SA1501CodeFixAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand element.
        /// </summary>
        internal static string SA1502CodeFix {
            get {
                return ResourceManager.GetString("SA1502CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# element containing opening and closing braces is written completely on a single line..
        /// </summary>
        internal static string SA1502Description {
            get {
                return ResourceManager.GetString("SA1502Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element should not be on a single line.
        /// </summary>
        internal static string SA1502MessageFormat {
            get {
                return ResourceManager.GetString("SA1502MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element should not be on a single line.
        /// </summary>
        internal static string SA1502Title {
            get {
                return ResourceManager.GetString("SA1502Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap with braces.
        /// </summary>
        internal static string SA1503CodeFix {
            get {
                return ResourceManager.GetString("SA1503CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reformat accessors to multiple lines style.
        /// </summary>
        internal static string SA1504CodeFixMultipleLines {
            get {
                return ResourceManager.GetString("SA1504CodeFixMultipleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reformat accessors to single line style.
        /// </summary>
        internal static string SA1504CodeFixSingleLine {
            get {
                return ResourceManager.GetString("SA1504CodeFixSingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank lines following this brace.
        /// </summary>
        internal static string SA1505CodeFix {
            get {
                return ResourceManager.GetString("SA1505CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank line(s) after documentation header.
        /// </summary>
        internal static string SA1506CodeFix {
            get {
                return ResourceManager.GetString("SA1506CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove multiple blank lines.
        /// </summary>
        internal static string SA1507CodeFix {
            get {
                return ResourceManager.GetString("SA1507CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank lines preceding this brace.
        /// </summary>
        internal static string SA1508CodeFix {
            get {
                return ResourceManager.GetString("SA1508CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank lines preceding this brace.
        /// </summary>
        internal static string SA1509CodeFix {
            get {
                return ResourceManager.GetString("SA1509CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank line before chained statement.
        /// </summary>
        internal static string SA1510CodeFix {
            get {
                return ResourceManager.GetString("SA1510CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank line before while.
        /// </summary>
        internal static string SA1511CodeFix {
            get {
                return ResourceManager.GetString("SA1511CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank line after comment.
        /// </summary>
        internal static string SA1512CodeFix {
            get {
                return ResourceManager.GetString("SA1512CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank line after brace.
        /// </summary>
        internal static string SA1513CodeFix {
            get {
                return ResourceManager.GetString("SA1513CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before documentation header.
        /// </summary>
        internal static string SA1514CodeFix {
            get {
                return ResourceManager.GetString("SA1514CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before comment.
        /// </summary>
        internal static string SA1515CodeFix {
            get {
                return ResourceManager.GetString("SA1515CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix blank lines.
        /// </summary>
        internal static string SA1516CodeFixAll {
            get {
                return ResourceManager.GetString("SA1516CodeFixAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new line.
        /// </summary>
        internal static string SA1516CodeFixInsert {
            get {
                return ResourceManager.GetString("SA1516CodeFixInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank line.
        /// </summary>
        internal static string SA1516CodeFixRemove {
            get {
                return ResourceManager.GetString("SA1516CodeFixRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjacent C# elements are not separated by a blank line..
        /// </summary>
        internal static string SA1516Description {
            get {
                return ResourceManager.GetString("SA1516Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjacent using directives should not be separated by a blank line..
        /// </summary>
        internal static string SA1516DescriptionOmit {
            get {
                return ResourceManager.GetString("SA1516DescriptionOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjacent using directives should be separated by a blank line..
        /// </summary>
        internal static string SA1516DescriptionRequire {
            get {
                return ResourceManager.GetString("SA1516DescriptionRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements should be separated by blank line.
        /// </summary>
        internal static string SA1516MessageFormat {
            get {
                return ResourceManager.GetString("SA1516MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directives should not be separated by blank line.
        /// </summary>
        internal static string SA1516MessageFormatOmit {
            get {
                return ResourceManager.GetString("SA1516MessageFormatOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directives should be separated by blank line.
        /// </summary>
        internal static string SA1516MessageFormatRequire {
            get {
                return ResourceManager.GetString("SA1516MessageFormatRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements should be separated by blank line.
        /// </summary>
        internal static string SA1516Title {
            get {
                return ResourceManager.GetString("SA1516Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank lines at the start of the file.
        /// </summary>
        internal static string SA1517CodeFix {
            get {
                return ResourceManager.GetString("SA1517CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix whitespace at the end of the file.
        /// </summary>
        internal static string SA1518CodeFix {
            get {
                return ResourceManager.GetString("SA1518CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should not contain blank lines at the end of the file.
        /// </summary>
        internal static string SA1518DescriptionAllow {
            get {
                return ResourceManager.GetString("SA1518DescriptionAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File may not end with a newline character.
        /// </summary>
        internal static string SA1518DescriptionOmit {
            get {
                return ResourceManager.GetString("SA1518DescriptionOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required to end with a single newline character.
        /// </summary>
        internal static string SA1518DescriptionRequire {
            get {
                return ResourceManager.GetString("SA1518DescriptionRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should not contain blank lines at the end of the file.
        /// </summary>
        internal static string SA1518MessageFormatAllow {
            get {
                return ResourceManager.GetString("SA1518MessageFormatAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File may not end with a newline character.
        /// </summary>
        internal static string SA1518MessageFormatOmit {
            get {
                return ResourceManager.GetString("SA1518MessageFormatOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required to end with a single newline character.
        /// </summary>
        internal static string SA1518MessageFormatRequire {
            get {
                return ResourceManager.GetString("SA1518MessageFormatRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use line endings correctly at end of file.
        /// </summary>
        internal static string SA1518Title {
            get {
                return ResourceManager.GetString("SA1518Title", resourceCulture);
            }
        }
    }
}
