//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.NamingRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NamingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.NamingRules.NamingResources", typeof(NamingResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename To &apos;{0}&apos;.
        /// </summary>
        internal static string RenameToCodeFix {
            get {
                return ResourceManager.GetString("RenameToCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a C# element does not begin with an upper-case letter..
        /// </summary>
        internal static string SA1300Description {
            get {
                return ResourceManager.GetString("SA1300Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; should begin with an uppercase letter.
        /// </summary>
        internal static string SA1300MessageFormat {
            get {
                return ResourceManager.GetString("SA1300MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element should begin with upper-case letter.
        /// </summary>
        internal static string SA1300Title {
            get {
                return ResourceManager.GetString("SA1300Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no situations in which this rule will fire..
        /// </summary>
        internal static string SA1301Description {
            get {
                return ResourceManager.GetString("SA1301Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element should begin with lower-case letter.
        /// </summary>
        internal static string SA1301MessageFormat {
            get {
                return ResourceManager.GetString("SA1301MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element should begin with lower-case letter.
        /// </summary>
        internal static string SA1301Title {
            get {
                return ResourceManager.GetString("SA1301Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix interface name with &apos;I&apos;.
        /// </summary>
        internal static string SA1302CodeFix {
            get {
                return ResourceManager.GetString("SA1302CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a C# interface does not begin with the capital letter I..
        /// </summary>
        internal static string SA1302Description {
            get {
                return ResourceManager.GetString("SA1302Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface names should begin with I.
        /// </summary>
        internal static string SA1302MessageFormat {
            get {
                return ResourceManager.GetString("SA1302MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface names should begin with I.
        /// </summary>
        internal static string SA1302Title {
            get {
                return ResourceManager.GetString("SA1302Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a constant C# field should begin with an upper-case letter..
        /// </summary>
        internal static string SA1303Description {
            get {
                return ResourceManager.GetString("SA1303Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Const field names should begin with upper-case letter.
        /// </summary>
        internal static string SA1303MessageFormat {
            get {
                return ResourceManager.GetString("SA1303MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Const field names should begin with upper-case letter.
        /// </summary>
        internal static string SA1303Title {
            get {
                return ResourceManager.GetString("SA1303Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a non-private readonly C# field should being with an upper-case letter..
        /// </summary>
        internal static string SA1304Description {
            get {
                return ResourceManager.GetString("SA1304Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-private readonly fields should begin with upper-case letter.
        /// </summary>
        internal static string SA1304MessageFormat {
            get {
                return ResourceManager.GetString("SA1304MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-private readonly fields should begin with upper-case letter.
        /// </summary>
        internal static string SA1304Title {
            get {
                return ResourceManager.GetString("SA1304Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a field or variable in C# uses Hungarian notation..
        /// </summary>
        internal static string SA1305Description {
            get {
                return ResourceManager.GetString("SA1305Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; should not use Hungarian notation.
        /// </summary>
        internal static string SA1305MessageFormat {
            get {
                return ResourceManager.GetString("SA1305MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names should not use Hungarian notation.
        /// </summary>
        internal static string SA1305Title {
            get {
                return ResourceManager.GetString("SA1305Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a field in C# does not begin with a lower-case letter..
        /// </summary>
        internal static string SA1306Description {
            get {
                return ResourceManager.GetString("SA1306Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; should begin with lower-case letter.
        /// </summary>
        internal static string SA1306MessageFormat {
            get {
                return ResourceManager.GetString("SA1306MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names should begin with lower-case letter.
        /// </summary>
        internal static string SA1306Title {
            get {
                return ResourceManager.GetString("SA1306Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a internal or internal field in C# does not begin with an upper-case letter..
        /// </summary>
        internal static string SA1307Description {
            get {
                return ResourceManager.GetString("SA1307Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; should begin with upper-case letter.
        /// </summary>
        internal static string SA1307MessageFormat {
            get {
                return ResourceManager.GetString("SA1307MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible fields should begin with upper-case letter.
        /// </summary>
        internal static string SA1307Title {
            get {
                return ResourceManager.GetString("SA1307Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field name in C# is prefixed with &apos;m_&apos;, &apos;s_&apos;, or &apos;t_&apos;..
        /// </summary>
        internal static string SA1308Description {
            get {
                return ResourceManager.GetString("SA1308Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; should not begin with the prefix &apos;{1}&apos;.
        /// </summary>
        internal static string SA1308MessageFormat {
            get {
                return ResourceManager.GetString("SA1308MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable names should not be prefixed.
        /// </summary>
        internal static string SA1308Title {
            get {
                return ResourceManager.GetString("SA1308Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field name in C# begins with an underscore..
        /// </summary>
        internal static string SA1309Description {
            get {
                return ResourceManager.GetString("SA1309Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; should not begin with an underscore.
        /// </summary>
        internal static string SA1309MessageFormat {
            get {
                return ResourceManager.GetString("SA1309MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names should not begin with underscore.
        /// </summary>
        internal static string SA1309Title {
            get {
                return ResourceManager.GetString("SA1309Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field name in C# contains an underscore..
        /// </summary>
        internal static string SA1310Description {
            get {
                return ResourceManager.GetString("SA1310Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; should not contain an underscore.
        /// </summary>
        internal static string SA1310MessageFormat {
            get {
                return ResourceManager.GetString("SA1310MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names should not contain underscore.
        /// </summary>
        internal static string SA1310Title {
            get {
                return ResourceManager.GetString("SA1310Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a static readonly field does not begin with an upper-case letter..
        /// </summary>
        internal static string SA1311Description {
            get {
                return ResourceManager.GetString("SA1311Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static readonly fields should begin with upper-case letter.
        /// </summary>
        internal static string SA1311MessageFormat {
            get {
                return ResourceManager.GetString("SA1311MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static readonly fields should begin with upper-case letter.
        /// </summary>
        internal static string SA1311Title {
            get {
                return ResourceManager.GetString("SA1311Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a variable in C# does not begin with a lower-case letter..
        /// </summary>
        internal static string SA1312Description {
            get {
                return ResourceManager.GetString("SA1312Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; should begin with lower-case letter.
        /// </summary>
        internal static string SA1312MessageFormat {
            get {
                return ResourceManager.GetString("SA1312MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable names should begin with lower-case letter.
        /// </summary>
        internal static string SA1312Title {
            get {
                return ResourceManager.GetString("SA1312Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a parameter in C# does not begin with a lower-case letter..
        /// </summary>
        internal static string SA1313Description {
            get {
                return ResourceManager.GetString("SA1313Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; should begin with lower-case letter.
        /// </summary>
        internal static string SA1313MessageFormat {
            get {
                return ResourceManager.GetString("SA1313MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter names should begin with lower-case letter.
        /// </summary>
        internal static string SA1313Title {
            get {
                return ResourceManager.GetString("SA1313Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix type parameter name with &apos;T&apos;.
        /// </summary>
        internal static string SA1314CodeFix {
            get {
                return ResourceManager.GetString("SA1314CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a C# type parameter does not begin with the capital letter T..
        /// </summary>
        internal static string SA1314Description {
            get {
                return ResourceManager.GetString("SA1314Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type parameter names should begin with T.
        /// </summary>
        internal static string SA1314MessageFormat {
            get {
                return ResourceManager.GetString("SA1314MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type parameter names should begin with T.
        /// </summary>
        internal static string SA1314Title {
            get {
                return ResourceManager.GetString("SA1314Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct tuple element name casing.
        /// </summary>
        internal static string SA1316CodeFix {
            get {
                return ResourceManager.GetString("SA1316CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element names within a tuple type should have the correct casing..
        /// </summary>
        internal static string SA1316Description {
            get {
                return ResourceManager.GetString("SA1316Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuple element names should use correct casing.
        /// </summary>
        internal static string SA1316MessageFormat {
            get {
                return ResourceManager.GetString("SA1316MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuple element names should use correct casing.
        /// </summary>
        internal static string SA1316Title {
            get {
                return ResourceManager.GetString("SA1316Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field name in C# does not begin with an underscore..
        /// </summary>
        internal static string SX1309Description {
            get {
                return ResourceManager.GetString("SX1309Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; should begin with an underscore.
        /// </summary>
        internal static string SX1309MessageFormat {
            get {
                return ResourceManager.GetString("SX1309MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A static field name in C# does not begin with an underscore..
        /// </summary>
        internal static string SX1309SDescription {
            get {
                return ResourceManager.GetString("SX1309SDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static field &apos;{0}&apos; should begin with an underscore.
        /// </summary>
        internal static string SX1309SMessageFormat {
            get {
                return ResourceManager.GetString("SX1309SMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static field names should begin with underscore.
        /// </summary>
        internal static string SX1309STitle {
            get {
                return ResourceManager.GetString("SX1309STitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names should begin with underscore.
        /// </summary>
        internal static string SX1309Title {
            get {
                return ResourceManager.GetString("SX1309Title", resourceCulture);
            }
        }
    }
}
