// <auto-generated/>

#nullable enable
using System.Reflection;


namespace StyleCop.Analyzers.SpecialRules
{
    internal static partial class SpecialResources
    {
        private static global::System.Resources.ResourceManager? s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(SpecialResources)));
        internal static global::System.Globalization.CultureInfo? Culture { get; set; }
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string? GetResourceString(string resourceKey, string? defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture) ?? defaultValue;
        /// <summary>XML comment analysis can only be performed when the project is configured to parse documentation comments. To enable this functionality, update the project to produce an XML documentation file as part of the build.</summary>
        internal static string? @SA0001Description => GetResourceString("SA0001Description");
        /// <summary>XML comment analysis is disabled due to project configuration</summary>
        internal static string? @SA0001MessageFormat => GetResourceString("SA0001MessageFormat");
        /// <summary>XML comment analysis disabled</summary>
        internal static string? @SA0001Title => GetResourceString("SA0001Title");
        /// <summary>Various errors in the stylecop.json file can prevent the file from being loaded by the analyzers. In this case, the default settings are used instead.
        /// 
        /// {0}</summary>
        internal static string? @SA0002Description => GetResourceString("SA0002Description");
        /// <summary>The stylecop.json settings file could not be loaded</summary>
        internal static string? @SA0002MessageFormat => GetResourceString("SA0002MessageFormat");
        /// <summary>Invalid settings file</summary>
        internal static string? @SA0002Title => GetResourceString("SA0002Title");

    }
}
