// <auto-generated/>

#nullable enable
using System.Reflection;


namespace StyleCop.Analyzers.Helpers
{
    internal static partial class HelpersResources
    {
        private static global::System.Resources.ResourceManager? s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(HelpersResources)));
        internal static global::System.Globalization.CultureInfo? Culture { get; set; }
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string? GetResourceString(string resourceKey, string? defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture) ?? defaultValue;
        /// <summary>Fix all '{0}'</summary>
        internal static string? @FixAllOccurrencesOfDiagnostic => GetResourceString("FixAllOccurrencesOfDiagnostic");
        /// <summary>Fix all '{0}' in '{1}'</summary>
        internal static string? @FixAllOccurrencesOfDiagnosticInScope => GetResourceString("FixAllOccurrencesOfDiagnosticInScope");
        /// <summary>Fix all '{0}' in Solution</summary>
        internal static string? @FixAllOccurrencesOfDiagnosticInSolution => GetResourceString("FixAllOccurrencesOfDiagnosticInSolution");

    }
}
