//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.SpacingRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpacingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpacingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.SpacingRules.SpacingResources", typeof(SpacingResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1003CodeFix {
            get {
                return ResourceManager.GetString("SA1003CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1004CodeFix {
            get {
                return ResourceManager.GetString("SA1004CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A line within a documentation header above a C# element does not begin with a single space..
        /// </summary>
        internal static string SA1004Description {
            get {
                return ResourceManager.GetString("SA1004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation line must begin with a space..
        /// </summary>
        internal static string SA1004MessageFormat {
            get {
                return ResourceManager.GetString("SA1004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation lines must begin with single space.
        /// </summary>
        internal static string SA1004Title {
            get {
                return ResourceManager.GetString("SA1004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1005CodeFix {
            get {
                return ResourceManager.GetString("SA1005CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single-line comment within a C# code file does not begin with a single space..
        /// </summary>
        internal static string SA1005Description {
            get {
                return ResourceManager.GetString("SA1005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single line comment must begin with a space..
        /// </summary>
        internal static string SA1005MessageFormat {
            get {
                return ResourceManager.GetString("SA1005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single line comments must begin with single space.
        /// </summary>
        internal static string SA1005Title {
            get {
                return ResourceManager.GetString("SA1005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# preprocessor-type keyword is preceded by space..
        /// </summary>
        internal static string SA1006Description {
            get {
                return ResourceManager.GetString("SA1006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessor keyword &apos;{0}&apos; must not be preceded by a space..
        /// </summary>
        internal static string SA1006MessageFormat {
            get {
                return ResourceManager.GetString("SA1006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessor keywords must not be preceded by space.
        /// </summary>
        internal static string SA1006Title {
            get {
                return ResourceManager.GetString("SA1006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator keyword within a C# operator overload method is not followed by any whitespace..
        /// </summary>
        internal static string SA1007Description {
            get {
                return ResourceManager.GetString("SA1007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator keyword must be followed by a space..
        /// </summary>
        internal static string SA1007MessageFormat {
            get {
                return ResourceManager.GetString("SA1007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator keyword must be followed by space.
        /// </summary>
        internal static string SA1007Title {
            get {
                return ResourceManager.GetString("SA1007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1008CodeFix {
            get {
                return ResourceManager.GetString("SA1008CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An opening attribute bracket within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1016Description {
            get {
                return ResourceManager.GetString("SA1016Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening attribute brackets must not be followed by a space..
        /// </summary>
        internal static string SA1016MessageFormat {
            get {
                return ResourceManager.GetString("SA1016MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening attribute brackets must be spaced correctly.
        /// </summary>
        internal static string SA1016Title {
            get {
                return ResourceManager.GetString("SA1016Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A closing attribute bracket within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1017Description {
            get {
                return ResourceManager.GetString("SA1017Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing attribute brackets must not be preceded by a space..
        /// </summary>
        internal static string SA1017MessageFormat {
            get {
                return ResourceManager.GetString("SA1017MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing attribute brackets must be spaced correctly.
        /// </summary>
        internal static string SA1017Title {
            get {
                return ResourceManager.GetString("SA1017Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1018CodeFix {
            get {
                return ResourceManager.GetString("SA1018CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nullable type symbol within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1018Description {
            get {
                return ResourceManager.GetString("SA1018Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable type symbol must not be preceded by a space..
        /// </summary>
        internal static string SA1018MessageFormat {
            get {
                return ResourceManager.GetString("SA1018MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable type symbols must be spaced correctly.
        /// </summary>
        internal static string SA1018Title {
            get {
                return ResourceManager.GetString("SA1018Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1025CodeFix {
            get {
                return ResourceManager.GetString("SA1025CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code contains multiple whitespace characters in a row..
        /// </summary>
        internal static string SA1025Description {
            get {
                return ResourceManager.GetString("SA1025Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must not contain multiple whitespace characters in a row..
        /// </summary>
        internal static string SA1025MessageFormat {
            get {
                return ResourceManager.GetString("SA1025MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must not contain multiple whitespace in a row.
        /// </summary>
        internal static string SA1025Title {
            get {
                return ResourceManager.GetString("SA1025Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An implicitly typed new array allocation within a C# code file is not spaced correctly..
        /// </summary>
        internal static string SA1026Description {
            get {
                return ResourceManager.GetString("SA1026Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;new&apos; must not be followed by a space or a blank line..
        /// </summary>
        internal static string SA1026MessageFormat {
            get {
                return ResourceManager.GetString("SA1026MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must not contain space after new keyword in implicitly typed array allocation.
        /// </summary>
        internal static string SA1026Title {
            get {
                return ResourceManager.GetString("SA1026Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace tabs with spaces.
        /// </summary>
        internal static string SA1027CodeFix {
            get {
                return ResourceManager.GetString("SA1027CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C# code contains a tab character.
        /// </summary>
        internal static string SA1027Description {
            get {
                return ResourceManager.GetString("SA1027Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs must not be used..
        /// </summary>
        internal static string SA1027MessageFormat {
            get {
                return ResourceManager.GetString("SA1027MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs must not be used.
        /// </summary>
        internal static string SA1027Title {
            get {
                return ResourceManager.GetString("SA1027Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove trailing whitespace.
        /// </summary>
        internal static string SA1028CodeFix {
            get {
                return ResourceManager.GetString("SA1028CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should not be any whitespace at the end of a line of code..
        /// </summary>
        internal static string SA1028Description {
            get {
                return ResourceManager.GetString("SA1028Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must not contain trailing whitespace.
        /// </summary>
        internal static string SA1028MessageFormat {
            get {
                return ResourceManager.GetString("SA1028MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must not contain trailing whitespace.
        /// </summary>
        internal static string SA1028Title {
            get {
                return ResourceManager.GetString("SA1028Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string TokenSpacingCodeFix {
            get {
                return ResourceManager.GetString("TokenSpacingCodeFix", resourceCulture);
            }
        }
    }
}
