//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.SpacingRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpacingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpacingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.SpacingRules.SpacingResources", typeof(SpacingResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spacing around a C# keyword is incorrect..
        /// </summary>
        internal static string SA1000Description {
            get {
                return ResourceManager.GetString("SA1000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;{0}&apos; should{1} be followed by a space.
        /// </summary>
        internal static string SA1000MessageFormat {
            get {
                return ResourceManager.GetString("SA1000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords should be spaced correctly.
        /// </summary>
        internal static string SA1000Title {
            get {
                return ResourceManager.GetString("SA1000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spacing around a comma is incorrect, within a C# code file..
        /// </summary>
        internal static string SA1001Description {
            get {
                return ResourceManager.GetString("SA1001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commas should{0} be {1} by whitespace.
        /// </summary>
        internal static string SA1001MessageFormat {
            get {
                return ResourceManager.GetString("SA1001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commas should be spaced correctly.
        /// </summary>
        internal static string SA1001Title {
            get {
                return ResourceManager.GetString("SA1001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spacing around a semicolon is incorrect, within a C# code file..
        /// </summary>
        internal static string SA1002Description {
            get {
                return ResourceManager.GetString("SA1002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolons should{0} be {1} by a space.
        /// </summary>
        internal static string SA1002MessageFormat {
            get {
                return ResourceManager.GetString("SA1002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolons should be spaced correctly.
        /// </summary>
        internal static string SA1002Title {
            get {
                return ResourceManager.GetString("SA1002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1003CodeFix {
            get {
                return ResourceManager.GetString("SA1003CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spacing around an operator symbol is incorrect, within a C# code file..
        /// </summary>
        internal static string SA1003Description {
            get {
                return ResourceManager.GetString("SA1003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; should be followed by whitespace..
        /// </summary>
        internal static string SA1003MessageFormatFollowedByWhitespace {
            get {
                return ResourceManager.GetString("SA1003MessageFormatFollowedByWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; should not appear at the end of a line..
        /// </summary>
        internal static string SA1003MessageFormatNotAtEndOfLine {
            get {
                return ResourceManager.GetString("SA1003MessageFormatNotAtEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; should not be followed by a comment..
        /// </summary>
        internal static string SA1003MessageFormatNotFollowedByComment {
            get {
                return ResourceManager.GetString("SA1003MessageFormatNotFollowedByComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; should not be followed by whitespace..
        /// </summary>
        internal static string SA1003MessageFormatNotFollowedByWhitespace {
            get {
                return ResourceManager.GetString("SA1003MessageFormatNotFollowedByWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; should not be preceded by whitespace..
        /// </summary>
        internal static string SA1003MessageFormatNotPrecededByWhitespace {
            get {
                return ResourceManager.GetString("SA1003MessageFormatNotPrecededByWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; should be preceded by whitespace..
        /// </summary>
        internal static string SA1003MessageFormatPrecededByWhitespace {
            get {
                return ResourceManager.GetString("SA1003MessageFormatPrecededByWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols should be spaced correctly.
        /// </summary>
        internal static string SA1003Title {
            get {
                return ResourceManager.GetString("SA1003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1004CodeFix {
            get {
                return ResourceManager.GetString("SA1004CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A line within a documentation header above a C# element does not begin with a single space..
        /// </summary>
        internal static string SA1004Description {
            get {
                return ResourceManager.GetString("SA1004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation line should begin with a space.
        /// </summary>
        internal static string SA1004MessageFormat {
            get {
                return ResourceManager.GetString("SA1004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation lines should begin with single space.
        /// </summary>
        internal static string SA1004Title {
            get {
                return ResourceManager.GetString("SA1004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1005CodeFix {
            get {
                return ResourceManager.GetString("SA1005CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single-line comment within a C# code file does not begin with a single space..
        /// </summary>
        internal static string SA1005Description {
            get {
                return ResourceManager.GetString("SA1005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single line comment should begin with a space.
        /// </summary>
        internal static string SA1005MessageFormat {
            get {
                return ResourceManager.GetString("SA1005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single line comments should begin with single space.
        /// </summary>
        internal static string SA1005Title {
            get {
                return ResourceManager.GetString("SA1005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# preprocessor-type keyword is preceded by space..
        /// </summary>
        internal static string SA1006Description {
            get {
                return ResourceManager.GetString("SA1006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessor keyword &apos;{0}&apos; should not be preceded by a space.
        /// </summary>
        internal static string SA1006MessageFormat {
            get {
                return ResourceManager.GetString("SA1006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessor keywords should not be preceded by space.
        /// </summary>
        internal static string SA1006Title {
            get {
                return ResourceManager.GetString("SA1006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator keyword within a C# operator overload method is not followed by any whitespace..
        /// </summary>
        internal static string SA1007Description {
            get {
                return ResourceManager.GetString("SA1007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator keyword should be followed by a space.
        /// </summary>
        internal static string SA1007MessageFormat {
            get {
                return ResourceManager.GetString("SA1007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator keyword should be followed by space.
        /// </summary>
        internal static string SA1007Title {
            get {
                return ResourceManager.GetString("SA1007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1008CodeFix {
            get {
                return ResourceManager.GetString("SA1008CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An opening parenthesis within a C# statement is not spaced correctly..
        /// </summary>
        internal static string SA1008Description {
            get {
                return ResourceManager.GetString("SA1008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening parenthesis should not be followed by a space..
        /// </summary>
        internal static string SA1008MessageNotFollowed {
            get {
                return ResourceManager.GetString("SA1008MessageNotFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening parenthesis should not be preceded by a space..
        /// </summary>
        internal static string SA1008MessageNotPreceded {
            get {
                return ResourceManager.GetString("SA1008MessageNotPreceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening parenthesis should be preceded by a space..
        /// </summary>
        internal static string SA1008MessagePreceded {
            get {
                return ResourceManager.GetString("SA1008MessagePreceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening parenthesis should be spaced correctly.
        /// </summary>
        internal static string SA1008Title {
            get {
                return ResourceManager.GetString("SA1008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A closing parenthesis within a C# statement is not spaced correctly..
        /// </summary>
        internal static string SA1009Description {
            get {
                return ResourceManager.GetString("SA1009Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing parenthesis should be followed by a space.
        /// </summary>
        internal static string SA1009MessageFollowed {
            get {
                return ResourceManager.GetString("SA1009MessageFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing parenthesis should not be followed by a space.
        /// </summary>
        internal static string SA1009MessageNotFollowed {
            get {
                return ResourceManager.GetString("SA1009MessageNotFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing parenthesis should not be preceded by a space.
        /// </summary>
        internal static string SA1009MessageNotPreceded {
            get {
                return ResourceManager.GetString("SA1009MessageNotPreceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing parenthesis should be spaced correctly.
        /// </summary>
        internal static string SA1009Title {
            get {
                return ResourceManager.GetString("SA1009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An opening square bracket within a C# statement is not spaced correctly..
        /// </summary>
        internal static string SA1010Description {
            get {
                return ResourceManager.GetString("SA1010Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening square brackets should not be followed by a space.
        /// </summary>
        internal static string SA1010MessageNotFollowed {
            get {
                return ResourceManager.GetString("SA1010MessageNotFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening square brackets should not be preceded by a space.
        /// </summary>
        internal static string SA1010MessageNotPreceded {
            get {
                return ResourceManager.GetString("SA1010MessageNotPreceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening square brackets should be spaced correctly.
        /// </summary>
        internal static string SA1010Title {
            get {
                return ResourceManager.GetString("SA1010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A closing square bracket within a C# statement is not spaced correctly..
        /// </summary>
        internal static string SA1011Description {
            get {
                return ResourceManager.GetString("SA1011Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing square bracket should{0} be {1} by a space.
        /// </summary>
        internal static string SA1011MessageFormat {
            get {
                return ResourceManager.GetString("SA1011MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing square brackets should be spaced correctly.
        /// </summary>
        internal static string SA1011Title {
            get {
                return ResourceManager.GetString("SA1011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An opening brace within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1012Description {
            get {
                return ResourceManager.GetString("SA1012Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening brace should{0} be {1} by a space.
        /// </summary>
        internal static string SA1012MessageFormat {
            get {
                return ResourceManager.GetString("SA1012MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening braces should be spaced correctly.
        /// </summary>
        internal static string SA1012Title {
            get {
                return ResourceManager.GetString("SA1012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A closing brace within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1013Description {
            get {
                return ResourceManager.GetString("SA1013Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing brace should{0} be {1} by a space.
        /// </summary>
        internal static string SA1013MessageFormat {
            get {
                return ResourceManager.GetString("SA1013MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing braces should be spaced correctly.
        /// </summary>
        internal static string SA1013Title {
            get {
                return ResourceManager.GetString("SA1013Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An opening generic bracket within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1014Description {
            get {
                return ResourceManager.GetString("SA1014Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening generic brackets should not be {0} by a space.
        /// </summary>
        internal static string SA1014MessageFormat {
            get {
                return ResourceManager.GetString("SA1014MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening generic brackets should be spaced correctly.
        /// </summary>
        internal static string SA1014Title {
            get {
                return ResourceManager.GetString("SA1014Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A closing generic bracket within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1015Description {
            get {
                return ResourceManager.GetString("SA1015Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing generic bracket should be followed by a space.
        /// </summary>
        internal static string SA1015MessageFollowed {
            get {
                return ResourceManager.GetString("SA1015MessageFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing generic bracket should not be followed by a space.
        /// </summary>
        internal static string SA1015MessageNotFollowed {
            get {
                return ResourceManager.GetString("SA1015MessageNotFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing generic bracket should not be preceded by a space.
        /// </summary>
        internal static string SA1015MessageNotPreceded {
            get {
                return ResourceManager.GetString("SA1015MessageNotPreceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing generic brackets should be spaced correctly.
        /// </summary>
        internal static string SA1015Title {
            get {
                return ResourceManager.GetString("SA1015Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An opening attribute bracket within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1016Description {
            get {
                return ResourceManager.GetString("SA1016Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening attribute brackets should not be followed by a space.
        /// </summary>
        internal static string SA1016MessageFormat {
            get {
                return ResourceManager.GetString("SA1016MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening attribute brackets should be spaced correctly.
        /// </summary>
        internal static string SA1016Title {
            get {
                return ResourceManager.GetString("SA1016Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A closing attribute bracket within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1017Description {
            get {
                return ResourceManager.GetString("SA1017Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing attribute brackets should not be preceded by a space.
        /// </summary>
        internal static string SA1017MessageFormat {
            get {
                return ResourceManager.GetString("SA1017MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing attribute brackets should be spaced correctly.
        /// </summary>
        internal static string SA1017Title {
            get {
                return ResourceManager.GetString("SA1017Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1018CodeFix {
            get {
                return ResourceManager.GetString("SA1018CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nullable type symbol within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1018Description {
            get {
                return ResourceManager.GetString("SA1018Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable type symbol should not be preceded by a space.
        /// </summary>
        internal static string SA1018MessageFormat {
            get {
                return ResourceManager.GetString("SA1018MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable type symbols should be spaced correctly.
        /// </summary>
        internal static string SA1018Title {
            get {
                return ResourceManager.GetString("SA1018Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spacing around a member access symbol is incorrect, within a C# code file..
        /// </summary>
        internal static string SA1019Description {
            get {
                return ResourceManager.GetString("SA1019Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member access symbol &apos;{0}&apos; should not be followed by a space.
        /// </summary>
        internal static string SA1019MessageNotFollowed {
            get {
                return ResourceManager.GetString("SA1019MessageNotFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member access symbol &apos;{0}&apos; should not be preceded by a space.
        /// </summary>
        internal static string SA1019MessageNotPreceded {
            get {
                return ResourceManager.GetString("SA1019MessageNotPreceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member access symbols should be spaced correctly.
        /// </summary>
        internal static string SA1019Title {
            get {
                return ResourceManager.GetString("SA1019Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An increment or decrement symbol within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1020Description {
            get {
                return ResourceManager.GetString("SA1020Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} symbol &apos;{1}&apos; should not be {2} by a space.
        /// </summary>
        internal static string SA1020MessageFormat {
            get {
                return ResourceManager.GetString("SA1020MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment decrement symbols should be spaced correctly.
        /// </summary>
        internal static string SA1020Title {
            get {
                return ResourceManager.GetString("SA1020Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A negative sign within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1021Description {
            get {
                return ResourceManager.GetString("SA1021Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative sign should{0} be {1} by a space.
        /// </summary>
        internal static string SA1021MessageFormat {
            get {
                return ResourceManager.GetString("SA1021MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative signs should be spaced correctly.
        /// </summary>
        internal static string SA1021Title {
            get {
                return ResourceManager.GetString("SA1021Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A positive sign within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1022Description {
            get {
                return ResourceManager.GetString("SA1022Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive sign should{0} be {1} by a space.
        /// </summary>
        internal static string SA1022MessageFormat {
            get {
                return ResourceManager.GetString("SA1022MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive signs should be spaced correctly.
        /// </summary>
        internal static string SA1022Title {
            get {
                return ResourceManager.GetString("SA1022Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dereference symbol or an access-of symbol within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1023Description {
            get {
                return ResourceManager.GetString("SA1023Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dereference symbol &apos;*&apos; should be followed by a space.
        /// </summary>
        internal static string SA1023MessageFollowed {
            get {
                return ResourceManager.GetString("SA1023MessageFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dereference symbol &apos;*&apos; should not appear at the beginning of a line.
        /// </summary>
        internal static string SA1023MessageNotAtBeginningOfLine {
            get {
                return ResourceManager.GetString("SA1023MessageNotAtBeginningOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dereference symbol &apos;*&apos; should not appear at the end of a line.
        /// </summary>
        internal static string SA1023MessageNotAtEndOfLine {
            get {
                return ResourceManager.GetString("SA1023MessageNotAtEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dereference symbol &apos;*&apos; should not be followed by a space.
        /// </summary>
        internal static string SA1023MessageNotFollowed {
            get {
                return ResourceManager.GetString("SA1023MessageNotFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dereference symbol &apos;*&apos; should not be preceded by a space.
        /// </summary>
        internal static string SA1023MessageNotPreceded {
            get {
                return ResourceManager.GetString("SA1023MessageNotPreceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dereference and access of symbols should be spaced correctly.
        /// </summary>
        internal static string SA1023Title {
            get {
                return ResourceManager.GetString("SA1023Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A colon within a C# element is not spaced correctly..
        /// </summary>
        internal static string SA1024Description {
            get {
                return ResourceManager.GetString("SA1024Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon should be followed by a space.
        /// </summary>
        internal static string SA1024MessageFollowed {
            get {
                return ResourceManager.GetString("SA1024MessageFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon should not be preceded by a space.
        /// </summary>
        internal static string SA1024MessageNotPreceded {
            get {
                return ResourceManager.GetString("SA1024MessageNotPreceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon should be preceded by a space.
        /// </summary>
        internal static string SA1024MessagePreceded {
            get {
                return ResourceManager.GetString("SA1024MessagePreceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colons Should Be Spaced Correctly.
        /// </summary>
        internal static string SA1024Title {
            get {
                return ResourceManager.GetString("SA1024Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string SA1025CodeFix {
            get {
                return ResourceManager.GetString("SA1025CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code contains multiple whitespace characters in a row..
        /// </summary>
        internal static string SA1025Description {
            get {
                return ResourceManager.GetString("SA1025Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should not contain multiple whitespace characters in a row.
        /// </summary>
        internal static string SA1025MessageFormat {
            get {
                return ResourceManager.GetString("SA1025MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should not contain multiple whitespace in a row.
        /// </summary>
        internal static string SA1025Title {
            get {
                return ResourceManager.GetString("SA1025Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An implicitly typed array allocation within a C# code file is not spaced correctly..
        /// </summary>
        internal static string SA1026Description {
            get {
                return ResourceManager.GetString("SA1026Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;{0}&apos; should not be followed by a space or a blank line.
        /// </summary>
        internal static string SA1026MessageFormat {
            get {
                return ResourceManager.GetString("SA1026MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should not contain space after new or stackalloc keyword in implicitly typed array allocation.
        /// </summary>
        internal static string SA1026Title {
            get {
                return ResourceManager.GetString("SA1026Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix tabs.
        /// </summary>
        internal static string SA1027CodeFix {
            get {
                return ResourceManager.GetString("SA1027CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code contains a tab or space character which is not consistent with the current project settings..
        /// </summary>
        internal static string SA1027Description {
            get {
                return ResourceManager.GetString("SA1027Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs and spaces should be used correctly.
        /// </summary>
        internal static string SA1027MessageFormat {
            get {
                return ResourceManager.GetString("SA1027MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use tabs correctly.
        /// </summary>
        internal static string SA1027Title {
            get {
                return ResourceManager.GetString("SA1027Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove trailing whitespace.
        /// </summary>
        internal static string SA1028CodeFix {
            get {
                return ResourceManager.GetString("SA1028CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should not be any whitespace at the end of a line of code..
        /// </summary>
        internal static string SA1028Description {
            get {
                return ResourceManager.GetString("SA1028Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should not contain trailing whitespace.
        /// </summary>
        internal static string SA1028MessageFormat {
            get {
                return ResourceManager.GetString("SA1028MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should not contain trailing whitespace.
        /// </summary>
        internal static string SA1028Title {
            get {
                return ResourceManager.GetString("SA1028Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix spacing.
        /// </summary>
        internal static string TokenSpacingCodeFix {
            get {
                return ResourceManager.GetString("TokenSpacingCodeFix", resourceCulture);
            }
        }
    }
}
