// <auto-generated/>
// https://raw.githubusercontent.com/dotnet/roslyn-analyzers/84fb81c27e0554eadf6b12f97eb52c7cd2803c7e/src/Utilities/Refactoring/ISyntaxKinds.cs

#nullable enable

// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the MIT license.  See License.txt in the project root for license information.

namespace Analyzer.Utilities
{
    internal interface ISyntaxKinds
    {
        int EndOfFileToken { get; }

        int ExpressionStatement { get; }
        int LocalDeclarationStatement { get; }

        int VariableDeclarator { get; }
    }
}
