//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.DocumentationRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.DocumentationRules.DocumentationResources", typeof(DocumentationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate constructor documentation.
        /// </summary>
        internal static string ConstructorDocumentationCodeFix {
            get {
                return ResourceManager.GetString("ConstructorDocumentationCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate destructor documentation.
        /// </summary>
        internal static string DestructorDocumentationCodeFix {
            get {
                return ResourceManager.GetString("DestructorDocumentationCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizes an instance of the .
        /// </summary>
        internal static string DestructorStandardTextFirstPart {
            get {
                return ResourceManager.GetString("DestructorStandardTextFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  class..
        /// </summary>
        internal static string DestructorStandardTextSecondPart {
            get {
                return ResourceManager.GetString("DestructorStandardTextSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit documentation.
        /// </summary>
        internal static string InheritdocCodeFix {
            get {
                return ResourceManager.GetString("InheritdocCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate method documentation.
        /// </summary>
        internal static string MethodDocumentationCodeFix {
            get {
                return ResourceManager.GetString("MethodDocumentationCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the .
        /// </summary>
        internal static string NonPrivateConstructorStandardTextFirstPart {
            get {
                return ResourceManager.GetString("NonPrivateConstructorStandardTextFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}.
        /// </summary>
        internal static string NonPrivateConstructorStandardTextSecondPart {
            get {
                return ResourceManager.GetString("NonPrivateConstructorStandardTextSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not used..
        /// </summary>
        internal static string ParameterNotUsed {
            get {
                return ResourceManager.GetString("ParameterNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents a default instance of the .
        /// </summary>
        internal static string PrivateConstructorStandardTextFirstPart {
            get {
                return ResourceManager.GetString("PrivateConstructorStandardTextFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} from being created.
        /// </summary>
        internal static string PrivateConstructorStandardTextSecondPart {
            get {
                return ResourceManager.GetString("PrivateConstructorStandardTextSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add standard text.
        /// </summary>
        internal static string PropertySummaryStartTextCodeFix {
            get {
                return ResourceManager.GetString("PropertySummaryStartTextCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# code element is missing a documentation header..
        /// </summary>
        internal static string SA1600Description {
            get {
                return ResourceManager.GetString("SA1600Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements should be documented.
        /// </summary>
        internal static string SA1600MessageFormat {
            get {
                return ResourceManager.GetString("SA1600MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements should be documented.
        /// </summary>
        internal static string SA1600Title {
            get {
                return ResourceManager.GetString("SA1600Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# partial element is missing a documentation header..
        /// </summary>
        internal static string SA1601Description {
            get {
                return ResourceManager.GetString("SA1601Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial elements should be documented.
        /// </summary>
        internal static string SA1601MessageFormat {
            get {
                return ResourceManager.GetString("SA1601MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial elements should be documented.
        /// </summary>
        internal static string SA1601Title {
            get {
                return ResourceManager.GetString("SA1601Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item within a C# enumeration is missing an Xml documentation header..
        /// </summary>
        internal static string SA1602Description {
            get {
                return ResourceManager.GetString("SA1602Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration items should be documented.
        /// </summary>
        internal static string SA1602MessageFormat {
            get {
                return ResourceManager.GetString("SA1602MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration items should be documented.
        /// </summary>
        internal static string SA1602Title {
            get {
                return ResourceManager.GetString("SA1602Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML within a C# element’s document header is badly formed..
        /// </summary>
        internal static string SA1603Description {
            get {
                return ResourceManager.GetString("SA1603Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation header is composed of invalid XML: {0}.
        /// </summary>
        internal static string SA1603MessageFormat {
            get {
                return ResourceManager.GetString("SA1603MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation should contain valid XML.
        /// </summary>
        internal static string SA1603Title {
            get {
                return ResourceManager.GetString("SA1603Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML header documentation for a C# element is missing a &lt;summary&gt; tag..
        /// </summary>
        internal static string SA1604Description {
            get {
                return ResourceManager.GetString("SA1604Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element documentation should have summary.
        /// </summary>
        internal static string SA1604MessageFormat {
            get {
                return ResourceManager.GetString("SA1604MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element documentation should have summary.
        /// </summary>
        internal static string SA1604Title {
            get {
                return ResourceManager.GetString("SA1604Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;summary&gt; or &lt;content&gt; tag within the documentation header for a C# code element is missing or empty..
        /// </summary>
        internal static string SA1605Description {
            get {
                return ResourceManager.GetString("SA1605Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial element documentation should have summary.
        /// </summary>
        internal static string SA1605MessageFormat {
            get {
                return ResourceManager.GetString("SA1605MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial element documentation should have summary.
        /// </summary>
        internal static string SA1605Title {
            get {
                return ResourceManager.GetString("SA1605Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;summary&gt; tag within the documentation header for a C# code element is empty..
        /// </summary>
        internal static string SA1606Description {
            get {
                return ResourceManager.GetString("SA1606Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element documentation should have summary text.
        /// </summary>
        internal static string SA1606MessageFormat {
            get {
                return ResourceManager.GetString("SA1606MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element documentation should have summary text.
        /// </summary>
        internal static string SA1606Title {
            get {
                return ResourceManager.GetString("SA1606Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;summary&gt; or &lt;content&gt; tag within the documentation header for a C# code element is empty..
        /// </summary>
        internal static string SA1607Description {
            get {
                return ResourceManager.GetString("SA1607Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial element documentation should have summary text.
        /// </summary>
        internal static string SA1607MessageFormat {
            get {
                return ResourceManager.GetString("SA1607MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial element documentation should have summary text.
        /// </summary>
        internal static string SA1607Title {
            get {
                return ResourceManager.GetString("SA1607Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;summary&gt; tag within an element&apos;s XML header documentation contains the default text generated by Visual Studio during the creation of the element..
        /// </summary>
        internal static string SA1608Description {
            get {
                return ResourceManager.GetString("SA1608Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element documentation should not have default summary.
        /// </summary>
        internal static string SA1608MessageFormat {
            get {
                return ResourceManager.GetString("SA1608MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element documentation should not have default summary.
        /// </summary>
        internal static string SA1608Title {
            get {
                return ResourceManager.GetString("SA1608Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML header documentation for a C# property does not contain a &lt;value&gt; tag..
        /// </summary>
        internal static string SA1609Description {
            get {
                return ResourceManager.GetString("SA1609Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property documentation should have value.
        /// </summary>
        internal static string SA1609MessageFormat {
            get {
                return ResourceManager.GetString("SA1609MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document value from summary.
        /// </summary>
        internal static string SA1609SA1610CodeFix {
            get {
                return ResourceManager.GetString("SA1609SA1610CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property documentation should have value.
        /// </summary>
        internal static string SA1609Title {
            get {
                return ResourceManager.GetString("SA1609Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML header documentation for a C# property contains an empty &lt;value&gt; tag..
        /// </summary>
        internal static string SA1610Description {
            get {
                return ResourceManager.GetString("SA1610Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property documentation should have value text.
        /// </summary>
        internal static string SA1610MessageFormat {
            get {
                return ResourceManager.GetString("SA1610MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property documentation should have value text.
        /// </summary>
        internal static string SA1610Title {
            get {
                return ResourceManager.GetString("SA1610Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# method, constructor, delegate or indexer element is missing documentation for one or more of its parameters..
        /// </summary>
        internal static string SA1611Description {
            get {
                return ResourceManager.GetString("SA1611Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation for parameter &apos;{0}&apos; is missing.
        /// </summary>
        internal static string SA1611MessageFormat {
            get {
                return ResourceManager.GetString("SA1611MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element parameters should be documented.
        /// </summary>
        internal static string SA1611Title {
            get {
                return ResourceManager.GetString("SA1611Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation describing the parameters to a C# method, constructor, delegate or indexer element does not match the actual parameters on the element..
        /// </summary>
        internal static string SA1612Description {
            get {
                return ResourceManager.GetString("SA1612Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SA1612MissingParamForDocumentationMessageFormat {
            get {
                return ResourceManager.GetString("SA1612MissingParamForDocumentationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter documentation for &apos;{0}&apos; should be at position {1}..
        /// </summary>
        internal static string SA1612ParamWrongOrderMessageFormat {
            get {
                return ResourceManager.GetString("SA1612ParamWrongOrderMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element parameter documentation should match element parameters.
        /// </summary>
        internal static string SA1612Title {
            get {
                return ResourceManager.GetString("SA1612Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;param&gt; tag within a C# element&apos;s documentation header is missing a name attribute containing the name of the parameter..
        /// </summary>
        internal static string SA1613Description {
            get {
                return ResourceManager.GetString("SA1613Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element parameter documentation should declare parameter name.
        /// </summary>
        internal static string SA1613MessageFormat {
            get {
                return ResourceManager.GetString("SA1613MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element parameter documentation should declare parameter name.
        /// </summary>
        internal static string SA1613Title {
            get {
                return ResourceManager.GetString("SA1613Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;param&gt; tag within a C# element&apos;s documentation header is empty..
        /// </summary>
        internal static string SA1614Description {
            get {
                return ResourceManager.GetString("SA1614Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element parameter documentation should have text.
        /// </summary>
        internal static string SA1614MessageFormat {
            get {
                return ResourceManager.GetString("SA1614MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element parameter documentation should have text.
        /// </summary>
        internal static string SA1614Title {
            get {
                return ResourceManager.GetString("SA1614Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# element is missing documentation for its return value..
        /// </summary>
        internal static string SA1615Description {
            get {
                return ResourceManager.GetString("SA1615Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element return value should be documented.
        /// </summary>
        internal static string SA1615MessageFormat {
            get {
                return ResourceManager.GetString("SA1615MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document return value.
        /// </summary>
        internal static string SA1615SA1616CodeFix {
            get {
                return ResourceManager.GetString("SA1615SA1616CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element return value should be documented.
        /// </summary>
        internal static string SA1615Title {
            get {
                return ResourceManager.GetString("SA1615Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;returns&gt; tag within a C# element&apos;s documentation header is empty..
        /// </summary>
        internal static string SA1616Description {
            get {
                return ResourceManager.GetString("SA1616Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element return value documentation should have text.
        /// </summary>
        internal static string SA1616MessageFormat {
            get {
                return ResourceManager.GetString("SA1616MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element return value documentation should have text.
        /// </summary>
        internal static string SA1616Title {
            get {
                return ResourceManager.GetString("SA1616Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &lt;returns&gt; XML comment.
        /// </summary>
        internal static string SA1617CodeFix {
            get {
                return ResourceManager.GetString("SA1617CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# code element does not contain a return value, or returns void, but the documentation header for the element contains a &lt;returns&gt; tag..
        /// </summary>
        internal static string SA1617Description {
            get {
                return ResourceManager.GetString("SA1617Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void return value should not be documented.
        /// </summary>
        internal static string SA1617MessageFormat {
            get {
                return ResourceManager.GetString("SA1617MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void return value should not be documented.
        /// </summary>
        internal static string SA1617Title {
            get {
                return ResourceManager.GetString("SA1617Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generic C# element is missing documentation for one or more of its generic type parameters..
        /// </summary>
        internal static string SA1618Description {
            get {
                return ResourceManager.GetString("SA1618Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation for type parameter &apos;{0}&apos; is missing.
        /// </summary>
        internal static string SA1618MessageFormat {
            get {
                return ResourceManager.GetString("SA1618MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic type parameters should be documented.
        /// </summary>
        internal static string SA1618Title {
            get {
                return ResourceManager.GetString("SA1618Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generic, partial C# element is missing documentation for one or more of its generic type parameters, and the documentation for the element contains a &lt;summary&gt; tag..
        /// </summary>
        internal static string SA1619Description {
            get {
                return ResourceManager.GetString("SA1619Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation for type parameter &apos;{0}&apos; is missing.
        /// </summary>
        internal static string SA1619MessageFormat {
            get {
                return ResourceManager.GetString("SA1619MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic type parameters should be documented partial class.
        /// </summary>
        internal static string SA1619Title {
            get {
                return ResourceManager.GetString("SA1619Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;typeparam&gt; tags within the Xml header documentation for a generic C# element do not match the generic type parameters on the element..
        /// </summary>
        internal static string SA1620Description {
            get {
                return ResourceManager.GetString("SA1620Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type parameter &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SA1620MissingMessageFormat {
            get {
                return ResourceManager.GetString("SA1620MissingMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic type parameter documentation should match type parameters.
        /// </summary>
        internal static string SA1620Title {
            get {
                return ResourceManager.GetString("SA1620Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type parameter documentation for &apos;{0}&apos; should be at position {1}..
        /// </summary>
        internal static string SA1620WrongOrderMessageFormat {
            get {
                return ResourceManager.GetString("SA1620WrongOrderMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;typeparam&gt; tag within the XML header documentation for a generic C# element is missing a name attribute, or contains an empty name attribute..
        /// </summary>
        internal static string SA1621Description {
            get {
                return ResourceManager.GetString("SA1621Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic type parameter documentation should declare parameter name..
        /// </summary>
        internal static string SA1621MessageFormat {
            get {
                return ResourceManager.GetString("SA1621MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic type parameter documentation should declare parameter name.
        /// </summary>
        internal static string SA1621Title {
            get {
                return ResourceManager.GetString("SA1621Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;typeparam&gt; tag within the Xml header documentation for a generic C# element is empty..
        /// </summary>
        internal static string SA1622Description {
            get {
                return ResourceManager.GetString("SA1622Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic type parameter documentation should have text..
        /// </summary>
        internal static string SA1622MessageFormat {
            get {
                return ResourceManager.GetString("SA1622MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic type parameter documentation should have text.
        /// </summary>
        internal static string SA1622Title {
            get {
                return ResourceManager.GetString("SA1622Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation text within a C# property’s &lt;summary&gt; tag does not match the accessors within the property..
        /// </summary>
        internal static string SA1623Description {
            get {
                return ResourceManager.GetString("SA1623Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property&apos;s documentation summary text should begin with: &apos;{0}&apos;.
        /// </summary>
        internal static string SA1623MessageFormat {
            get {
                return ResourceManager.GetString("SA1623MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property summary documentation should match accessors.
        /// </summary>
        internal static string SA1623Title {
            get {
                return ResourceManager.GetString("SA1623Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation text within a C# property’s &lt;summary&gt; tag takes into account all of the accessors within the property, but one of the accessors has limited access..
        /// </summary>
        internal static string SA1624Description {
            get {
                return ResourceManager.GetString("SA1624Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because the property only contains a visible {0} accessor, the documentation summary text should begin with &apos;{1}&apos;..
        /// </summary>
        internal static string SA1624MessageFormat {
            get {
                return ResourceManager.GetString("SA1624MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property summary documentation should omit accessor with restricted access.
        /// </summary>
        internal static string SA1624Title {
            get {
                return ResourceManager.GetString("SA1624Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Xml documentation for a C# element contains two or more identical entries, indicating that the documentation has been copied and pasted. This can sometimes indicate invalid or poorly written documentation..
        /// </summary>
        internal static string SA1625Description {
            get {
                return ResourceManager.GetString("SA1625Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element documentation should not be copied and pasted.
        /// </summary>
        internal static string SA1625MessageFormat {
            get {
                return ResourceManager.GetString("SA1625MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element documentation should not be copied and pasted.
        /// </summary>
        internal static string SA1625Title {
            get {
                return ResourceManager.GetString("SA1625Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to line comment.
        /// </summary>
        internal static string SA1626CodeFix {
            get {
                return ResourceManager.GetString("SA1626CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C# code contains a single-line comment which begins with three forward slashes in a row..
        /// </summary>
        internal static string SA1626Description {
            get {
                return ResourceManager.GetString("SA1626Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-line comments should not use documentation style slashes.
        /// </summary>
        internal static string SA1626MessageFormat {
            get {
                return ResourceManager.GetString("SA1626MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-line comments should not use documentation style slashes.
        /// </summary>
        internal static string SA1626Title {
            get {
                return ResourceManager.GetString("SA1626Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML header documentation for a C# code element contains an empty tag..
        /// </summary>
        internal static string SA1627Description {
            get {
                return ResourceManager.GetString("SA1627Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation text within the &apos;{0}&apos; tag should not be empty..
        /// </summary>
        internal static string SA1627MessageFormat {
            get {
                return ResourceManager.GetString("SA1627MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation text should not be empty.
        /// </summary>
        internal static string SA1627Title {
            get {
                return ResourceManager.GetString("SA1627Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section of the XML header documentation for a C# element does not begin with a capital letter..
        /// </summary>
        internal static string SA1628Description {
            get {
                return ResourceManager.GetString("SA1628Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Message format.
        /// </summary>
        internal static string SA1628MessageFormat {
            get {
                return ResourceManager.GetString("SA1628MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation text should begin with a capital letter.
        /// </summary>
        internal static string SA1628Title {
            get {
                return ResourceManager.GetString("SA1628Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add period.
        /// </summary>
        internal static string SA1629CodeFix {
            get {
                return ResourceManager.GetString("SA1629CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section of the XML header documentation for a C# element does not end with a period..
        /// </summary>
        internal static string SA1629Description {
            get {
                return ResourceManager.GetString("SA1629Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation text should end with a period.
        /// </summary>
        internal static string SA1629MessageFormat {
            get {
                return ResourceManager.GetString("SA1629MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation text should end with a period.
        /// </summary>
        internal static string SA1629Title {
            get {
                return ResourceManager.GetString("SA1629Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section of the XML header documentation for a C# element does not contain any whitespace between words..
        /// </summary>
        internal static string SA1630Description {
            get {
                return ResourceManager.GetString("SA1630Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Message format.
        /// </summary>
        internal static string SA1630MessageFormat {
            get {
                return ResourceManager.GetString("SA1630MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation text should contain whitespace.
        /// </summary>
        internal static string SA1630Title {
            get {
                return ResourceManager.GetString("SA1630Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section of the Xml header documentation for a C# element does not contain enough alphabetic characters..
        /// </summary>
        internal static string SA1631Description {
            get {
                return ResourceManager.GetString("SA1631Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Message format.
        /// </summary>
        internal static string SA1631MessageFormat {
            get {
                return ResourceManager.GetString("SA1631MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation should meet character percentage.
        /// </summary>
        internal static string SA1631Title {
            get {
                return ResourceManager.GetString("SA1631Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section of the Xml header documentation for a C# element is too short..
        /// </summary>
        internal static string SA1632Description {
            get {
                return ResourceManager.GetString("SA1632Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Message format.
        /// </summary>
        internal static string SA1632MessageFormat {
            get {
                return ResourceManager.GetString("SA1632MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation text should meet minimum character length.
        /// </summary>
        internal static string SA1632Title {
            get {
                return ResourceManager.GetString("SA1632Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file header.
        /// </summary>
        internal static string SA1633CodeFix {
            get {
                return ResourceManager.GetString("SA1633CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# code file is missing a standard file header..
        /// </summary>
        internal static string SA1633Description {
            get {
                return ResourceManager.GetString("SA1633Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header XML is invalid..
        /// </summary>
        internal static string SA1633MessageFormatMalformed {
            get {
                return ResourceManager.GetString("SA1633MessageFormatMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header is missing or not located at the top of the file..
        /// </summary>
        internal static string SA1633MessageFormatMissing {
            get {
                return ResourceManager.GetString("SA1633MessageFormatMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File should have header.
        /// </summary>
        internal static string SA1633Title {
            get {
                return ResourceManager.GetString("SA1633Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file is missing a copyright tag..
        /// </summary>
        internal static string SA1634Description {
            get {
                return ResourceManager.GetString("SA1634Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header should contain a copyright tag..
        /// </summary>
        internal static string SA1634MessageFormat {
            get {
                return ResourceManager.GetString("SA1634MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header should show copyright.
        /// </summary>
        internal static string SA1634Title {
            get {
                return ResourceManager.GetString("SA1634Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file is missing copyright text..
        /// </summary>
        internal static string SA1635Description {
            get {
                return ResourceManager.GetString("SA1635Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header should have copyright text.
        /// </summary>
        internal static string SA1635MessageFormat {
            get {
                return ResourceManager.GetString("SA1635MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header should have copyright text.
        /// </summary>
        internal static string SA1635Title {
            get {
                return ResourceManager.GetString("SA1635Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file does not contain the appropriate copyright text..
        /// </summary>
        internal static string SA1636Description {
            get {
                return ResourceManager.GetString("SA1636Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header copyright text should match the copyright text from the settings..
        /// </summary>
        internal static string SA1636MessageFormat {
            get {
                return ResourceManager.GetString("SA1636MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header copyright text should match.
        /// </summary>
        internal static string SA1636Title {
            get {
                return ResourceManager.GetString("SA1636Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file is missing the file name..
        /// </summary>
        internal static string SA1637Description {
            get {
                return ResourceManager.GetString("SA1637Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header should contain file name..
        /// </summary>
        internal static string SA1637MessageFormat {
            get {
                return ResourceManager.GetString("SA1637MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header should contain file name.
        /// </summary>
        internal static string SA1637Title {
            get {
                return ResourceManager.GetString("SA1637Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file attribute within copyright tag of the file header at the top of a C# code file does not contain the name of the file..
        /// </summary>
        internal static string SA1638Description {
            get {
                return ResourceManager.GetString("SA1638Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header file name documentation should match file name..
        /// </summary>
        internal static string SA1638MessageFormat {
            get {
                return ResourceManager.GetString("SA1638MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header file name documentation should match file name.
        /// </summary>
        internal static string SA1638Title {
            get {
                return ResourceManager.GetString("SA1638Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file does not contain a filled-in summary tag..
        /// </summary>
        internal static string SA1639Description {
            get {
                return ResourceManager.GetString("SA1639Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header should have summary.
        /// </summary>
        internal static string SA1639MessageFormat {
            get {
                return ResourceManager.GetString("SA1639MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header should have summary.
        /// </summary>
        internal static string SA1639Title {
            get {
                return ResourceManager.GetString("SA1639Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file does not contain company name text..
        /// </summary>
        internal static string SA1640Description {
            get {
                return ResourceManager.GetString("SA1640Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The copyright tag should contain a non-empty company attribute..
        /// </summary>
        internal static string SA1640MessageFormat {
            get {
                return ResourceManager.GetString("SA1640MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header should have valid company text.
        /// </summary>
        internal static string SA1640Title {
            get {
                return ResourceManager.GetString("SA1640Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file does not contain the appropriate company name text..
        /// </summary>
        internal static string SA1641Description {
            get {
                return ResourceManager.GetString("SA1641Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header company name should match the company name from the settings..
        /// </summary>
        internal static string SA1641MessageFormat {
            get {
                return ResourceManager.GetString("SA1641MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header company name text should match.
        /// </summary>
        internal static string SA1641Title {
            get {
                return ResourceManager.GetString("SA1641Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML documentation header for a C# constructor does not contain the appropriate summary text..
        /// </summary>
        internal static string SA1642Description {
            get {
                return ResourceManager.GetString("SA1642Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor summary documentation should begin with standard text.
        /// </summary>
        internal static string SA1642MessageFormat {
            get {
                return ResourceManager.GetString("SA1642MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add standard text.
        /// </summary>
        internal static string SA1642SA1643CodeFix {
            get {
                return ResourceManager.GetString("SA1642SA1643CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor summary documentation should begin with standard text.
        /// </summary>
        internal static string SA1642Title {
            get {
                return ResourceManager.GetString("SA1642Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML documentation header for a C# finalizer does not contain the appropriate summary text..
        /// </summary>
        internal static string SA1643Description {
            get {
                return ResourceManager.GetString("SA1643Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destructor summary documentation should begin with standard text.
        /// </summary>
        internal static string SA1643MessageFormat {
            get {
                return ResourceManager.GetString("SA1643MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destructor summary documentation should begin with standard text.
        /// </summary>
        internal static string SA1643Title {
            get {
                return ResourceManager.GetString("SA1643Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section within the XML documentation header for a C# element contains blank lines..
        /// </summary>
        internal static string SA1644Description {
            get {
                return ResourceManager.GetString("SA1644Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Message format.
        /// </summary>
        internal static string SA1644MessageFormat {
            get {
                return ResourceManager.GetString("SA1644MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation headers should not contain blank lines.
        /// </summary>
        internal static string SA1644Title {
            get {
                return ResourceManager.GetString("SA1644Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An included XML documentation file does not exist..
        /// </summary>
        internal static string SA1645Description {
            get {
                return ResourceManager.GetString("SA1645Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Message format.
        /// </summary>
        internal static string SA1645MessageFormat {
            get {
                return ResourceManager.GetString("SA1645MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included documentation file does not exist.
        /// </summary>
        internal static string SA1645Title {
            get {
                return ResourceManager.GetString("SA1645Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An included XML documentation link contains an invalid path..
        /// </summary>
        internal static string SA1646Description {
            get {
                return ResourceManager.GetString("SA1646Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Message format.
        /// </summary>
        internal static string SA1646MessageFormat {
            get {
                return ResourceManager.GetString("SA1646MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included documentation XPath does not exist.
        /// </summary>
        internal static string SA1646Title {
            get {
                return ResourceManager.GetString("SA1646Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An include tag within an XML documentation header does not contain valid file and path attribute..
        /// </summary>
        internal static string SA1647Description {
            get {
                return ResourceManager.GetString("SA1647Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Message format.
        /// </summary>
        internal static string SA1647MessageFormat {
            get {
                return ResourceManager.GetString("SA1647MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include node does not contain valid file and path.
        /// </summary>
        internal static string SA1647Title {
            get {
                return ResourceManager.GetString("SA1647Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;inheritdoc&gt; has been used on an element that doesn&apos;t inherit from a base class or implement an interface..
        /// </summary>
        internal static string SA1648Description {
            get {
                return ResourceManager.GetString("SA1648Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inheritdoc should be used with inheriting class.
        /// </summary>
        internal static string SA1648MessageFormat {
            get {
                return ResourceManager.GetString("SA1648MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inheritdoc should be used with inheriting class.
        /// </summary>
        internal static string SA1648Title {
            get {
                return ResourceManager.GetString("SA1648Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file to match first type name.
        /// </summary>
        internal static string SA1649CodeFix {
            get {
                return ResourceManager.GetString("SA1649CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name of a C# code file does not match the first type declared in the file..
        /// </summary>
        internal static string SA1649Description {
            get {
                return ResourceManager.GetString("SA1649Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name should match first type name..
        /// </summary>
        internal static string SA1649MessageFormat {
            get {
                return ResourceManager.GetString("SA1649MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name should match first type name.
        /// </summary>
        internal static string SA1649Title {
            get {
                return ResourceManager.GetString("SA1649Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element documentation for the element contains one or more spelling mistakes or unrecognized words..
        /// </summary>
        internal static string SA1650Description {
            get {
                return ResourceManager.GetString("SA1650Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Message format.
        /// </summary>
        internal static string SA1650MessageFormat {
            get {
                return ResourceManager.GetString("SA1650MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element documentation should be spelled correctly.
        /// </summary>
        internal static string SA1650Title {
            get {
                return ResourceManager.GetString("SA1650Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize placeholder text.
        /// </summary>
        internal static string SA1651CodeFix {
            get {
                return ResourceManager.GetString("SA1651CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element documentation contains a &lt;placeholder&gt; element..
        /// </summary>
        internal static string SA1651Description {
            get {
                return ResourceManager.GetString("SA1651Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use placeholder elements.
        /// </summary>
        internal static string SA1651MessageFormat {
            get {
                return ResourceManager.GetString("SA1651MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use placeholder elements.
        /// </summary>
        internal static string SA1651Title {
            get {
                return ResourceManager.GetString("SA1651Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets.
        /// </summary>
        internal static string StartingTextGets {
            get {
                return ResourceManager.GetString("StartingTextGets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets.
        /// </summary>
        internal static string StartingTextGetsOrSets {
            get {
                return ResourceManager.GetString("StartingTextGetsOrSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets a value indicating whether.
        /// </summary>
        internal static string StartingTextGetsOrSetsWhether {
            get {
                return ResourceManager.GetString("StartingTextGetsOrSetsWhether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a value indicating whether.
        /// </summary>
        internal static string StartingTextGetsWhether {
            get {
                return ResourceManager.GetString("StartingTextGetsWhether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        internal static string StartingTextReturns {
            get {
                return ResourceManager.GetString("StartingTextReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a value indicating whether.
        /// </summary>
        internal static string StartingTextReturnsWhether {
            get {
                return ResourceManager.GetString("StartingTextReturnsWhether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        internal static string StartingTextSets {
            get {
                return ResourceManager.GetString("StartingTextSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets a value indicating whether.
        /// </summary>
        internal static string StartingTextSetsWhether {
            get {
                return ResourceManager.GetString("StartingTextSetsWhether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes static members of the .
        /// </summary>
        internal static string StaticConstructorStandardTextFirstPart {
            get {
                return ResourceManager.GetString("StaticConstructorStandardTextFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}..
        /// </summary>
        internal static string StaticConstructorStandardTextSecondPart {
            get {
                return ResourceManager.GetString("StaticConstructorStandardTextSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A .
        /// </summary>
        internal static string TaskReturnElementFirstPart {
            get {
                return ResourceManager.GetString("TaskReturnElementFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  representing the result of the asynchronous operation..
        /// </summary>
        internal static string TaskReturnElementSecondPart {
            get {
                return ResourceManager.GetString("TaskReturnElementSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string TypeTextClass {
            get {
                return ResourceManager.GetString("TypeTextClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct.
        /// </summary>
        internal static string TypeTextStruct {
            get {
                return ResourceManager.GetString("TypeTextStruct", resourceCulture);
            }
        }
    }
}
