//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.DocumentationRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.DocumentationRules.DocumentationResources", typeof(DocumentationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit documentation.
        /// </summary>
        internal static string InheritdocCodeFix {
            get {
                return ResourceManager.GetString("InheritdocCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document value from summary.
        /// </summary>
        internal static string SA1609SA1610CodeFix {
            get {
                return ResourceManager.GetString("SA1609SA1610CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# method, constructor, delegate or indexer element is missing documentation for one or more of its parameters..
        /// </summary>
        internal static string SA1611Description {
            get {
                return ResourceManager.GetString("SA1611Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation for parameter &apos;{0}&apos; is missing.
        /// </summary>
        internal static string SA1611MessageFormat {
            get {
                return ResourceManager.GetString("SA1611MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element parameters must be documented.
        /// </summary>
        internal static string SA1611Title {
            get {
                return ResourceManager.GetString("SA1611Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document return value.
        /// </summary>
        internal static string SA1615SA1616CodeFix {
            get {
                return ResourceManager.GetString("SA1615SA1616CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &lt;returns&gt; XML comment.
        /// </summary>
        internal static string SA1617CodeFix {
            get {
                return ResourceManager.GetString("SA1617CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to line comment.
        /// </summary>
        internal static string SA1626CodeFix {
            get {
                return ResourceManager.GetString("SA1626CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML header documentation for a C# code element contains an empty tag..
        /// </summary>
        internal static string SA1627Description {
            get {
                return ResourceManager.GetString("SA1627Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation text within the \&apos;{0}\&apos; tag must not be empty..
        /// </summary>
        internal static string SA1627MessageFormat {
            get {
                return ResourceManager.GetString("SA1627MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation text must not be empty.
        /// </summary>
        internal static string SA1627Title {
            get {
                return ResourceManager.GetString("SA1627Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file header.
        /// </summary>
        internal static string SA1633CodeFix {
            get {
                return ResourceManager.GetString("SA1633CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# code file is missing a standard file header..
        /// </summary>
        internal static string SA1633Description {
            get {
                return ResourceManager.GetString("SA1633Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header XML is invalid..
        /// </summary>
        internal static string SA1633MessageFormatMalformed {
            get {
                return ResourceManager.GetString("SA1633MessageFormatMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header is missing or not located at the top of the file..
        /// </summary>
        internal static string SA1633MessageFormatMissing {
            get {
                return ResourceManager.GetString("SA1633MessageFormatMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must have header.
        /// </summary>
        internal static string SA1633Title {
            get {
                return ResourceManager.GetString("SA1633Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file is missing a copyright tag..
        /// </summary>
        internal static string SA1634Description {
            get {
                return ResourceManager.GetString("SA1634Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header must contain a copyright tag..
        /// </summary>
        internal static string SA1634MessageFormat {
            get {
                return ResourceManager.GetString("SA1634MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header must show copyright.
        /// </summary>
        internal static string SA1634Title {
            get {
                return ResourceManager.GetString("SA1634Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file is missing copyright text..
        /// </summary>
        internal static string SA1635Description {
            get {
                return ResourceManager.GetString("SA1635Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header must have copyright text.
        /// </summary>
        internal static string SA1635MessageFormat {
            get {
                return ResourceManager.GetString("SA1635MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header must have copyright text.
        /// </summary>
        internal static string SA1635Title {
            get {
                return ResourceManager.GetString("SA1635Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file does not contain the appropriate copyright text..
        /// </summary>
        internal static string SA1636Description {
            get {
                return ResourceManager.GetString("SA1636Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header copyright text must match the copyright text from the settings..
        /// </summary>
        internal static string SA1636MessageFormat {
            get {
                return ResourceManager.GetString("SA1636MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header copyright text must match.
        /// </summary>
        internal static string SA1636Title {
            get {
                return ResourceManager.GetString("SA1636Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file is missing the file name..
        /// </summary>
        internal static string SA1637Description {
            get {
                return ResourceManager.GetString("SA1637Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header must contain file name..
        /// </summary>
        internal static string SA1637MessageFormat {
            get {
                return ResourceManager.GetString("SA1637MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header must contain file name.
        /// </summary>
        internal static string SA1637Title {
            get {
                return ResourceManager.GetString("SA1637Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file attribute within copyright tag of the file header at the top of a C# code file does not contain the name of the file..
        /// </summary>
        internal static string SA1638Description {
            get {
                return ResourceManager.GetString("SA1638Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header file name documentation must match file name..
        /// </summary>
        internal static string SA1638MessageFormat {
            get {
                return ResourceManager.GetString("SA1638MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header file name documentation must match file name.
        /// </summary>
        internal static string SA1638Title {
            get {
                return ResourceManager.GetString("SA1638Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file does not contain a filled-in summary tag..
        /// </summary>
        internal static string SA1639Description {
            get {
                return ResourceManager.GetString("SA1639Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header must have summary.
        /// </summary>
        internal static string SA1639MessageFormat {
            get {
                return ResourceManager.GetString("SA1639MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header must have summary.
        /// </summary>
        internal static string SA1639Title {
            get {
                return ResourceManager.GetString("SA1639Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file does not contain company name text..
        /// </summary>
        internal static string SA1640Description {
            get {
                return ResourceManager.GetString("SA1640Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The copyright tag must contain a non-empty company attribute..
        /// </summary>
        internal static string SA1640MessageFormat {
            get {
                return ResourceManager.GetString("SA1640MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header must have valid company text.
        /// </summary>
        internal static string SA1640Title {
            get {
                return ResourceManager.GetString("SA1640Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header at the top of a C# code file does not contain the appropriate company name text..
        /// </summary>
        internal static string SA1641Description {
            get {
                return ResourceManager.GetString("SA1641Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file header company name must match the company name from the settings..
        /// </summary>
        internal static string SA1641MessageFormat {
            get {
                return ResourceManager.GetString("SA1641MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header company name text must match.
        /// </summary>
        internal static string SA1641Title {
            get {
                return ResourceManager.GetString("SA1641Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add standard text.
        /// </summary>
        internal static string SA1642SA1643CodeFix {
            get {
                return ResourceManager.GetString("SA1642SA1643CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file to match first type name.
        /// </summary>
        internal static string SA1649CodeFix {
            get {
                return ResourceManager.GetString("SA1649CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name of a C# code file does not match the first type declared in the file..
        /// </summary>
        internal static string SA1649Description {
            get {
                return ResourceManager.GetString("SA1649Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must match first type name..
        /// </summary>
        internal static string SA1649MessageFormat {
            get {
                return ResourceManager.GetString("SA1649MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must match first type name.
        /// </summary>
        internal static string SA1649Title {
            get {
                return ResourceManager.GetString("SA1649Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize placeholder text.
        /// </summary>
        internal static string SA1651CodeFix {
            get {
                return ResourceManager.GetString("SA1651CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is currently configured to not parse XML documentation comments; all diagnostics for documentation comments are disabled. Enable XML documentation output to enable these diagnostics..
        /// </summary>
        internal static string SA1652Description {
            get {
                return ResourceManager.GetString("SA1652Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable XML documentation output.
        /// </summary>
        internal static string SA1652MessageFormat {
            get {
                return ResourceManager.GetString("SA1652MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable XML documentation output.
        /// </summary>
        internal static string SA1652Title {
            get {
                return ResourceManager.GetString("SA1652Title", resourceCulture);
            }
        }
    }
}
