//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.OrderingRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.OrderingRules.OrderingResources", typeof(OrderingResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix element order.
        /// </summary>
        internal static string ElementOrderCodeFix {
            get {
                return ResourceManager.GetString("ElementOrderCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix modifier order.
        /// </summary>
        internal static string ModifierOrderCodeFix {
            get {
                return ResourceManager.GetString("ModifierOrderCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element within a C# code file is out of order in relation to the other elements in the code..
        /// </summary>
        internal static string SA1201Description {
            get {
                return ResourceManager.GetString("SA1201Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} should not follow a {1}.
        /// </summary>
        internal static string SA1201MessageFormat {
            get {
                return ResourceManager.GetString("SA1201MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements should appear in the correct order.
        /// </summary>
        internal static string SA1201Title {
            get {
                return ResourceManager.GetString("SA1201Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element within a C# code file is out of order in relation to other elements in the code..
        /// </summary>
        internal static string SA1202Description {
            get {
                return ResourceManager.GetString("SA1202Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; members should come before &apos;{1}&apos; members.
        /// </summary>
        internal static string SA1202MessageFormat {
            get {
                return ResourceManager.GetString("SA1202MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements should be ordered by access.
        /// </summary>
        internal static string SA1202Title {
            get {
                return ResourceManager.GetString("SA1202Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A constant field is placed beneath a non-constant field..
        /// </summary>
        internal static string SA1203Description {
            get {
                return ResourceManager.GetString("SA1203Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant fields should appear before non-constant fields.
        /// </summary>
        internal static string SA1203MessageFormat {
            get {
                return ResourceManager.GetString("SA1203MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants should appear before fields.
        /// </summary>
        internal static string SA1203Title {
            get {
                return ResourceManager.GetString("SA1203Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A static element is positioned beneath an instance element..
        /// </summary>
        internal static string SA1204Description {
            get {
                return ResourceManager.GetString("SA1204Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static members should appear before non-static members.
        /// </summary>
        internal static string SA1204MessageFormat {
            get {
                return ResourceManager.GetString("SA1204MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static elements should appear before instance elements.
        /// </summary>
        internal static string SA1204Title {
            get {
                return ResourceManager.GetString("SA1204Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add access modifier.
        /// </summary>
        internal static string SA1205CodeFix {
            get {
                return ResourceManager.GetString("SA1205CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place keyword &apos;protected&apos; before keyword &apos;internal&apos;.
        /// </summary>
        internal static string SA1207CodeFix {
            get {
                return ResourceManager.GetString("SA1207CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix accessor order.
        /// </summary>
        internal static string SA1213CodeFix {
            get {
                return ResourceManager.GetString("SA1213CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A readonly field is positioned beneath a non-readonly field..
        /// </summary>
        internal static string SA1214Description {
            get {
                return ResourceManager.GetString("SA1214Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly fields should appear before non-readonly fields.
        /// </summary>
        internal static string SA1214MessageFormat {
            get {
                return ResourceManager.GetString("SA1214MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly fields should appear before non-readonly fields.
        /// </summary>
        internal static string SA1214Title {
            get {
                return ResourceManager.GetString("SA1214Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder using statements.
        /// </summary>
        internal static string UsingCodeFix {
            get {
                return ResourceManager.GetString("UsingCodeFix", resourceCulture);
            }
        }
    }
}
