//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCop.Analyzers.OrderingRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCop.Analyzers.OrderingRules.OrderingResources", typeof(OrderingResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix element order.
        /// </summary>
        internal static string ElementOrderCodeFix {
            get {
                return ResourceManager.GetString("ElementOrderCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix modifier order.
        /// </summary>
        internal static string ModifierOrderCodeFix {
            get {
                return ResourceManager.GetString("ModifierOrderCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# using directive is placed outside of a namespace element..
        /// </summary>
        internal static string SA1200DescriptionInside {
            get {
                return ResourceManager.GetString("SA1200DescriptionInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A C# using directive is placed inside of a namespace declaration..
        /// </summary>
        internal static string SA1200DescriptionOutside {
            get {
                return ResourceManager.GetString("SA1200DescriptionOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directive should appear within a namespace declaration.
        /// </summary>
        internal static string SA1200MessageFormatInside {
            get {
                return ResourceManager.GetString("SA1200MessageFormatInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directive should appear outside a namespace declaration.
        /// </summary>
        internal static string SA1200MessageFormatOutside {
            get {
                return ResourceManager.GetString("SA1200MessageFormatOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directives should be placed correctly.
        /// </summary>
        internal static string SA1200Title {
            get {
                return ResourceManager.GetString("SA1200Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element within a C# code file is out of order in relation to the other elements in the code..
        /// </summary>
        internal static string SA1201Description {
            get {
                return ResourceManager.GetString("SA1201Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} should not follow a {1}.
        /// </summary>
        internal static string SA1201MessageFormat {
            get {
                return ResourceManager.GetString("SA1201MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements should appear in the correct order.
        /// </summary>
        internal static string SA1201Title {
            get {
                return ResourceManager.GetString("SA1201Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element within a C# code file is out of order in relation to other elements in the code..
        /// </summary>
        internal static string SA1202Description {
            get {
                return ResourceManager.GetString("SA1202Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; members should come before &apos;{1}&apos; members.
        /// </summary>
        internal static string SA1202MessageFormat {
            get {
                return ResourceManager.GetString("SA1202MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements should be ordered by access.
        /// </summary>
        internal static string SA1202Title {
            get {
                return ResourceManager.GetString("SA1202Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A constant field is placed beneath a non-constant field..
        /// </summary>
        internal static string SA1203Description {
            get {
                return ResourceManager.GetString("SA1203Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant fields should appear before non-constant fields.
        /// </summary>
        internal static string SA1203MessageFormat {
            get {
                return ResourceManager.GetString("SA1203MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants should appear before fields.
        /// </summary>
        internal static string SA1203Title {
            get {
                return ResourceManager.GetString("SA1203Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A static element is positioned beneath an instance element..
        /// </summary>
        internal static string SA1204Description {
            get {
                return ResourceManager.GetString("SA1204Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static members should appear before non-static members.
        /// </summary>
        internal static string SA1204MessageFormat {
            get {
                return ResourceManager.GetString("SA1204MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static elements should appear before instance elements.
        /// </summary>
        internal static string SA1204Title {
            get {
                return ResourceManager.GetString("SA1204Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add access modifier.
        /// </summary>
        internal static string SA1205CodeFix {
            get {
                return ResourceManager.GetString("SA1205CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partial element does not have an access modifier defined..
        /// </summary>
        internal static string SA1205Description {
            get {
                return ResourceManager.GetString("SA1205Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial elements should declare an access modifier.
        /// </summary>
        internal static string SA1205MessageFormat {
            get {
                return ResourceManager.GetString("SA1205MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial elements should declare access.
        /// </summary>
        internal static string SA1205Title {
            get {
                return ResourceManager.GetString("SA1205Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keywords within the declaration of an element do not follow a standard ordering scheme..
        /// </summary>
        internal static string SA1206Description {
            get {
                return ResourceManager.GetString("SA1206Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; modifier should appear before &apos;{1}&apos;.
        /// </summary>
        internal static string SA1206MessageFormat {
            get {
                return ResourceManager.GetString("SA1206MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration keywords should follow order.
        /// </summary>
        internal static string SA1206Title {
            get {
                return ResourceManager.GetString("SA1206Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place keyword &apos;protected&apos; before keyword &apos;internal&apos;.
        /// </summary>
        internal static string SA1207CodeFix {
            get {
                return ResourceManager.GetString("SA1207CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;{0}&apos; is positioned after the keyword &apos;{1}&apos; within the declaration of a {0} {1} C# element..
        /// </summary>
        internal static string SA1207Description {
            get {
                return ResourceManager.GetString("SA1207Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;{0}&apos; should come before &apos;{1}&apos;.
        /// </summary>
        internal static string SA1207MessageFormat {
            get {
                return ResourceManager.GetString("SA1207MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected should come before internal.
        /// </summary>
        internal static string SA1207Title {
            get {
                return ResourceManager.GetString("SA1207Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A using directive which declares a member of the &apos;System&apos; namespace appears after a using directive which declares a member of a different namespace, within a C# code file..
        /// </summary>
        internal static string SA1208Description {
            get {
                return ResourceManager.GetString("SA1208Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directive for &apos;{0}&apos; should appear before directive for &apos;{1}&apos;.
        /// </summary>
        internal static string SA1208MessageFormat {
            get {
                return ResourceManager.GetString("SA1208MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System using directives should be placed before other using directives.
        /// </summary>
        internal static string SA1208Title {
            get {
                return ResourceManager.GetString("SA1208Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A using-alias directive is positioned before a regular using directive..
        /// </summary>
        internal static string SA1209Description {
            get {
                return ResourceManager.GetString("SA1209Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using alias directives should be placed after all using namespace directives.
        /// </summary>
        internal static string SA1209MessageFormat {
            get {
                return ResourceManager.GetString("SA1209MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using alias directives should be placed after other using directives.
        /// </summary>
        internal static string SA1209Title {
            get {
                return ResourceManager.GetString("SA1209Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The using directives within a C# code file are not sorted alphabetically by namespace..
        /// </summary>
        internal static string SA1210Description {
            get {
                return ResourceManager.GetString("SA1210Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directives should be ordered alphabetically by the namespaces.
        /// </summary>
        internal static string SA1210MessageFormat {
            get {
                return ResourceManager.GetString("SA1210MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using directives should be ordered alphabetically by namespace.
        /// </summary>
        internal static string SA1210Title {
            get {
                return ResourceManager.GetString("SA1210Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The using-alias directives within a C# code file are not sorted alphabetically by alias name..
        /// </summary>
        internal static string SA1211Description {
            get {
                return ResourceManager.GetString("SA1211Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using alias directive for &apos;{0}&apos; should appear before using alias directive for &apos;{1}&apos;.
        /// </summary>
        internal static string SA1211MessageFormat {
            get {
                return ResourceManager.GetString("SA1211MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using alias directives should be ordered alphabetically by alias name.
        /// </summary>
        internal static string SA1211Title {
            get {
                return ResourceManager.GetString("SA1211Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A get accessor appears after a set accessor within a property or indexer..
        /// </summary>
        internal static string SA1212Description {
            get {
                return ResourceManager.GetString("SA1212Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A get accessor appears after a set accessor within a property or indexer.
        /// </summary>
        internal static string SA1212MessageFormat {
            get {
                return ResourceManager.GetString("SA1212MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property accessors should follow order.
        /// </summary>
        internal static string SA1212Title {
            get {
                return ResourceManager.GetString("SA1212Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix accessor order.
        /// </summary>
        internal static string SA1213CodeFix {
            get {
                return ResourceManager.GetString("SA1213CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An add accessor appears after a remove accessor within an event..
        /// </summary>
        internal static string SA1213Description {
            get {
                return ResourceManager.GetString("SA1213Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event accessors should follow order.
        /// </summary>
        internal static string SA1213MessageFormat {
            get {
                return ResourceManager.GetString("SA1213MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event accessors should follow order.
        /// </summary>
        internal static string SA1213Title {
            get {
                return ResourceManager.GetString("SA1213Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A readonly field is positioned beneath a non-readonly field..
        /// </summary>
        internal static string SA1214Description {
            get {
                return ResourceManager.GetString("SA1214Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly fields should appear before non-readonly fields.
        /// </summary>
        internal static string SA1214MessageFormat {
            get {
                return ResourceManager.GetString("SA1214MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly fields should appear before non-readonly fields.
        /// </summary>
        internal static string SA1214Title {
            get {
                return ResourceManager.GetString("SA1214Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A using static directive is positioned before a regular or after an alias using directive..
        /// </summary>
        internal static string SA1216Description {
            get {
                return ResourceManager.GetString("SA1216Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using static directives should be placed at the correct location.
        /// </summary>
        internal static string SA1216MessageFormat {
            get {
                return ResourceManager.GetString("SA1216MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using static directives should be placed at the correct location.
        /// </summary>
        internal static string SA1216Title {
            get {
                return ResourceManager.GetString("SA1216Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All using static directives should be ordered alphabetically..
        /// </summary>
        internal static string SA1217Description {
            get {
                return ResourceManager.GetString("SA1217Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The using static directive for &apos;{0}&apos; should appear after the using static directive for &apos;{1}&apos;.
        /// </summary>
        internal static string SA1217MessageFormat {
            get {
                return ResourceManager.GetString("SA1217MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using static directives should be ordered alphabetically.
        /// </summary>
        internal static string SA1217Title {
            get {
                return ResourceManager.GetString("SA1217Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder using statements.
        /// </summary>
        internal static string UsingCodeFix {
            get {
                return ResourceManager.GetString("UsingCodeFix", resourceCulture);
            }
        }
    }
}
